#!/bin/bash

#######################################################################################
#Nom du script	: ianRipper                                                           
#Description	: Ce script conçu avec la distribution Ubuntu permet de ripper des DVD.                                                                                  
#Auteur       	: Yann Le Coz                                           
#######################################################################################

# Définition et initialisation des variables
DEV='/dev/dvd'
DEST="${HOME}/Vidéos/movies_storage"
reset='O'
name="$(lsdvd ${DEV} 2>/dev/null | awk 'NR==1 {print $3}' | sed 's/.*/\L&/; s/[a-z]*/\u&/g; s/_/ /g')"
titleToEncode="$(lsdvd ${DEV} 2>/dev/null | awk 'END{print $3}')"
audio='fre,eng,spa'
subtitle='fre'
fileFormat='mp4'
audioEncoder='copy:dtshd'
audioMixing='5point1'
preset='Super HQ 1080p30 Surround'

# Fonction permettant de ripper les DVD
function rip_dvd
{
	if [ $1 = true ]
	then
		echo -e "\nEncodage en cours, cela peut prendre quelques minutes."
		if [ ${audio} = 'fre' ]
		then
			HandBrakeCLI -c 02 -i ${DEV} -o "${DEST}/${name}"_preview.${fileFormat} -E ${audioEncoder} -s 'none' -t ${titleToEncode} --audio-lang-list ${audio} --mixdown ${audioMixing/./point} --preset "${preset}" --two-pass 2>"${DEST}/${name}"_preview.log
		else
			HandBrakeCLI -c 02 -i ${DEV} -o "${DEST}/${name}"_preview.${fileFormat} -E ${audioEncoder} -t ${titleToEncode} --audio-lang-list ${audio} --mixdown ${audioMixing/./point} --preset "${preset}" --subtitle-lang-list ${subtitle} --subtitle-forced ${subtitle} --two-pass 2>"${DEST}/${name}"_preview.log
		fi
		# On supprime le fichier de log
		rm -f "${DEST}/${name}"_preview.log
		read -ep $'\n''Terminé !'$'\n'""${name}"_preview.${fileFormat} est dans ${DEST}/."$'\n\nVoulez-vous ripper le film en entier ? [O/N]'$'\n> '
		while [ -z ${REPLY} ]
		do
			read -p '> '
		done
	else
		echo -e "\nEncodage en cours, cela peut prendre quelques heures."
		if [ ${audio} = 'fre' ]
		then
			HandBrakeCLI -i ${DEV} -o "${DEST}/${name}".${fileFormat} -E ${audioEncoder} -s 'none' -t ${titleToEncode} --audio-lang-list ${audio} --mixdown ${audioMixing/./point} --preset "${preset}" --two-pass 2>"${DEST}/${name}".log
		else
			HandBrakeCLI -i ${DEV} -o "${DEST}/${name}".${fileFormat} -E ${audioEncoder} -t ${titleToEncode} --audio-lang-list ${audio} --mixdown ${audioMixing/./point} --preset "${preset}" --subtitle-lang-list ${subtitle} --subtitle-forced ${subtitle} --two-pass 2>"${DEST}/${name}".log
		fi

		# Suppression le fichier de log
		rm -f "${DEST}/${name}".log
		echo -e "\nTerminé !\n${name}.${fileFormat} est dans ${DEST}/.\n\nianRipper by Yann Le Coz"
	fi
}

# Fonction attribuant un code ISO 639-2 à une langue
function assign_language
{
	if [ "${#1}" -eq 3 ]
	then
		echo "\t$1" | sed 's/fre/Français/g' | sed 's/eng/Anglais/g' | sed 's/spa/Espagnol/g'
	else
		echo "\t$1" | sed 's/,/\n\t\t/g' | sed 's/fre/Français/g' | sed 's/eng/Anglais/g' | sed 's/spa/Espagnol/g'
	fi
}

# Vérification que les paquets requis sont installés
if ! `command -v lsdvd > /dev/null` && ! `command -v HandBrakeCLI > /dev/null`
then
	echo -e "\nVeuillez installer les paquets:\n  lsdvd\n  handbrake-cli"
	exit
elif ! `command -v lsdvd > /dev/null`
then
	echo -e "\nVeuillez installer le paquet:\n  lsdvd"
	exit
elif ! `command -v HandBrakeCLI > /dev/null`
then
	echo -e "\nVeuillez installer le paquet:\n  handbrake-cli"
	exit
fi

# Vérification qu'un DVD est bien inséré dans le lecteur
lsdvd ${DEV} > /dev/null 2>&1
if [ $? != 0 ]
then
	echo -e "\nAucune donnée trouvée. Veuillez vous assurer que vous avez inséré un DVD lisible et que votre lecteur fonctionne."
	exit
fi

# Vérification de l'existence du dossier de destination
if [ ! -d "${DEST}" ]
then
	echo -e "\n${DEST} n'existe pas.\nCréation du dossier."
	mkdir ${DEST}
fi

# Vérification que l'utilisateur n'entre pas de paramètres
if [ "$#" -ne 0 ]
then
	echo "Vous avez entré des paramètres."
	exit
else
	echo -e "\nTitre du film:\t${name}\nQualité:\t${preset}\nFormat:\t\t${fileFormat}\nPiste audio:`assign_language ${audio}`\nSous-titre:`assign_language ${subtitle}`\nSon:\t\t${audioEncoder/copy:/}\nMixage audio:\t${audioMixing/point/.}\n"
	
	# Demande à l'utilisateur s'il souhaite modifier des paramètres
	read -p 'Voulez-vous changer des paramètres ? [O/N]'$'\n> ' PARAM;
	while [ -z ${PARAM} ]
	do
		read -p '> '
	done
	if [ ${PARAM^^} = 'O' ]
	then
		while [ ${reset^^} = 'O' ]
		do
			read -ep 'Quel paramètre souhaitez-vous changer ?'$'\n> ' NAMEPARAM;
			case ${NAMEPARAM,,} in
			'titre du film')
				read -p '> Entrez le titre du film: ' name;;
			'qualité')
				read -p '> Entrez la qualité de la vidéo: ' preset;;
			'format')
				read -p '> Entrez le format du fichier: ' fileFormat;;
			'piste audio')
				read -p '> Entrez la piste audio: ' audio;;
			'sous-titre')
				read -p '> Entrez la langue du/des sous-titre(s): ' subtitle;
				;;
			'son')
				read -p "> Entrez l'encodage sonore: " audioEncoder;;
			'mixage audio')
				read -p '> Entrez le mixage audio: ' audioMixing;;
			*)
				echo -e '\nParamètre inconnu.\n'
				exit;;
			esac
			if [ ${audio} = 'fre' ]
			then
				echo -e "\nTitre du film:\t${name}\nQualité:\t${preset}\nFormat:\t\t${fileFormat}\nPiste audio:\t`assign_language ${audio}`\nSous-titre:\tAucun\nSon:\t\t${audioEncoder/copy:/}\nMixage audio:\t${audioMixing/point/.}\n"
			else
				echo -e "\nTitre du film:\t${name}\nQualité:\t${preset}\nFormat:\t\t${fileFormat}\nPiste audio:\t`assign_language ${audio}`\nSous-titre:\t`assign_language ${subtitle}`\nSon:\t\t${audioEncoder/copy:/}\nMixage audio:\t${audioMixing/point/.}\n"
			fi
			read -p 'Souhaitez-vous changer un autre paramètre ? [O/N]'$'\n> ' reset;
		done
	elif [ ${PARAM^^} != 'O' ] && [ ${PARAM^^} != 'N' ]
	then
		echo -e "\nOption inconnue.\n"
		exit
	fi
fi

# Demande à l'utilisateur s'il veut avoir un aperçu de la vidéo
read -p $'\n'"Voulez-vous un aperçu de la vidéo ? [O/N]"$'\n> '
while [ -z ${REPLY} ]
do
	read -p '> '
done
if [ ${REPLY^^} = 'O' ]
then
	rip_dvd true
	if [ ${REPLY^^} = 'O' ]
	then
		# Suppression de l'aperçu de la vidéo
		if [ -f "${DEST}/${name}"_preview.${fileFormat} ]
		then
			rm -f "${DEST}/${name}"_preview.${fileFormat}
		fi
		rip_dvd false
	else
		echo -e "\nianRipper by Yann Le Coz"
		exit
	fi
elif [ ${REPLY^^} = 'N' ]
then
	rip_dvd false
else
	echo -e '\nOption inconnue.\n'
	exit
fi
